spring:
  cloud:
    stream:
      bindings:
        order-input-channel:
          destination: user
        order-homedelivery-output-channel:
          destination: home-service
        order-take-away-output-channel:
          destination: take-away-service
      kafka:        binder:          brokers: localhost:9092
          
          
          
